name: Maven Testing

on:
  push:
    branches: ["master"]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ubuntu-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ubuntu-maven-

      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: ls -R target

      - name: Start application
        run: |
          nohup java -jar target/re-minder.jar & 
          for i in {1..30}; do # Wait for up to 30 seconds
            if curl -s http://localhost:8080/api/auth/health; then
              echo "Application is running"
              break
            fi
            echo "Waiting for application to start..."
            sleep 1
          done

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: macos-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            macos-maven-
            
      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: ls -R target

      - name: Start application
        run: |
          nohup java -jar target/re-minder.jar & 
          for i in {1..30}; do # Wait for up to 30 seconds
            if curl -s http://localhost:8080/api/auth/health; then
              echo "Application is running"
              break
            fi
            echo "Waiting for application to start..."
            sleep 1
          done

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: windows-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            windows-maven-
            
      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: dir target # Use `dir` command for Windows

      - name: Start application
        run: |
          Start-Process -NoNewWindow -FilePath "java" -ArgumentList "-jar target/re-minder.jar"
          $maxAttempts = 40
          $attempt = 0
          while ($attempt -lt $maxAttempts) {
            try {
              $response = Invoke-WebRequest -Uri "http://localhost:8080/api/auth/health" -UseBasicParsing
              if ($response.StatusCode -eq 200) {
                Write-Host "Application is running"
                break
              }
            } catch {
              Write-Host "Waiting for application to start..."
            }
            Start-Sleep -Seconds 1
            $attempt++
          }
          if ($attempt -eq $maxAttempts) {
            Write-Error "Application did not start within the expected time"
            exit 1
          }

      - name: Test endpoint step
        run: |
          try {
            $response = Invoke-WebRequest -Uri "http://localhost:8080/api/auth/health" -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "Application is running"
              break
            }
          } catch {
            Write-Host "Waiting for application to start..."
          }

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
