name: Maven Testing

on:
  push:
    branches: ["master"]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ubuntu-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ubuntu-maven-

      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: ls -R target

      - name: Start application
        run: |
          nohup java -jar target/re-minder.jar & 
          for i in {1..30}; do # Wait for up to 30 seconds
            if curl -s http://localhost:8080/api/auth/health; then
              echo "Application is running"
              break
            fi
            echo "Waiting for application to start..."
            sleep 1
          done

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: macos-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            macos-maven-

      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: ls -R target

      - name: Start application
        run: |
          nohup java -jar target/re-minder.jar & 
          for i in {1..30}; do # Wait for up to 30 seconds
            if curl -s http://localhost:8080/api/auth/health; then
              echo "Application is running"
              break
            fi
            echo "Waiting for application to start..."
            sleep 1
          done

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: windows-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            windows-maven-

      - name: Build application
        run: mvn clean package -DskipTests -DfinalName=re-minder -DoutputDirectory=target/

      - name: List build artifacts
        run: dir target # Use `dir` for Windows

      - name: Start application
        shell: cmd
        run: |
          start /b java -jar target/re-minder.jar
          for /l %%i in (1,1,30) do (
              curl -s http://localhost:8080/api/auth/health && (
                echo Application is running
                exit /b 0
              )
              echo Waiting for application to start...
              timeout /t 1 > nul
          )
          echo Application failed to start
          exit /b 1

      - name: Check application status
        shell: pwsh
        run: |
          try {
            $response = Invoke-WebRequest -Uri "http://localhost:8080/api/auth/health" -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "Application is still running"
              Write-Host "Response from endpoint: $($response.Content)"
            } else {
              Write-Host "Application returned unexpected status code: $($response.StatusCode)"
              exit 1
            }
          } catch {
            Write-Host "Application is not running or endpoint is unreachable."
            exit 1
          }

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
